system_logger:
  level: debug
  destination: stdout
  formatter: text

pip:
  listen_addr: ":443"
  ssl_cert: cert.pem
  ssl_cert_key: key.pem
  ca_certs_to_verify_client_certs:
    - ca.pem

database:
  url: "host=postgres port=5400 user=ztsnlac password=my$ecretPa$$w0rd sslmode=disable dbname=ztsnlac_db"